<?php

namespace App\Views;

use App\App;
use App\Comment\Comment;
use Core\Forms\Form;

class FeedbackForm extends Form
{
    protected $data = [
        'attr' => [
            'method' => 'POST',
            'class' => 'feedbackForm'
        ],
        'fields' => [
            'feedback' => [
                'type' => 'text',
                'label' => 'Parašykite atsiliepimą',
                'attr' => [
                    'class' => 'feedback-input'
                ],
                'extra' => [
                    'validators' => [
                        'validate_not_empty',
                        'validate_length' => [
                            500,
                        ],
                    ],
                ],
            ],
        ],
        'buttons' => [
            'send' => [
                'type' => 'submit',
                'value' => 'Siųsti',
                'name' => 'action',
                'title' => 'Siųsti'
            ],
        ],

        'callbacks' => [
            'success' => 'form_success',
            'fail' => 'form_fail',
        ],
    ];

    public function __construct()
    {
        parent::__construct($this->data);

    }

    public function formSuccess($filtered_input, $form)
    {
        $comment = new Comment(['comment' => $filtered_input['feedback'], 'name' => (App::$session->getUser())->getName()]);
        $insertSuccess = App::$comment_repository->insert($comment);
        if ($insertSuccess) {
            $allComments = App::$comment_repository->load();
            $newComment = $allComments[sizeof($allComments) - 1];
            return ['success' => true, $newComment];
        } else {
            return ['success' => false,];
        }
    }

    public function formFail($filtered_input, $form)
    {

        $response = new \Core\Api\Response();
        $errors = [];
        foreach ($form['fields'] as $field_id => $field) {
            if (isset($field['error'])) {
                $response->addError($field['error'], $field_id);
            }
        }
        $response->print();
    }

    public function render($templatePath = '')
    {
        return parent::render('../core/templates/form/form.tpl.php'); // TODO: Change the autogenerated stub
    }
}
