<?php

namespace App\Views;

use Core\Forms\Form;

class FeedbackForm extends Form
{
    protected $data = [
        'attr' => [
            'method' => 'POST',
            'class' => 'feedbackForm'
        ],
        'fields' => [
            'feedback' => [
                'type' => 'text',
                'label' => 'Atsiliepimas',
                'attr' => [
                    'placeholder' => 'Parašykite komentarą apie mus!',
                    'class' => 'feedback-input'
                ],
            ],
        ],
        'buttons' => [
            'send' => [
                'type' => 'submit',
                'value' => 'Siųsti',
                'name' => 'action',
                'title' => 'Siųsti'
            ],
        ],

        'callbacks' => [
            'success' => 'form_success',
            'fail' => 'form_fail',
        ],
    ];

    public function __construct()
    {
        parent::__construct($this->data);

    }

//    public function formSuccess($filtered_input, $data)
//    {
//
//        $user = new User($filtered_input);
//        App::$user_repository->insert($user);
//        header('location:/login');
//
//    }
//
//    public function formFail($filtered_input, $data)
//    {
//
//        try {
//            return $this->render();
//        } catch (\Exception $e) {
//        }
//    }

    public function render($templatePath = '')
    {
        return parent::render('../core/templates/form/form.tpl.php'); // TODO: Change the autogenerated stub
    }
}
