<?php

namespace App\Views;

use App\App;
use App\Controller\HomeController;
use Core\Forms\Form;
use Core\User\User;


class LoginForm extends Form
{
    protected $data = [
        'attr' => [
            'method' => 'POST',
            'class' => 'loginForm',
        ],
        'fields' => [
            'email' => [
                'type' => 'email',
                'label' => 'El. paštas',
                'attr' => [
                    'class' => 'email'
                ],
                'extra' => [
                    'validators' => [
                        'validate_not_empty',
                        'validate_is_email',
                        'validate_is_registered'
                    ],
                ],
            ],
            'password' => [
                'type' => 'password',
                'label' => 'Slaptažodis',
                'attr' => [
                    'class' => 'password'
                ],
                'extra' => [
                    'validators' => [
                        'validate_not_empty',
                    ],
                ],
            ],

        ],
        'buttons' => [
            'Login' => [
                'type' => 'submit',
                'value' => 'login',
                'name' => 'action',
                'title' => 'Login'
            ],
        ],
        'validators' => [
            'validate_email_and_password' => [
                'email',
                'password'
            ]
        ],
        'callbacks' => [
            'success' => 'form_success',
            'fail' => 'form_fail',
        ],
    ];

    public function __construct()
    {
        parent::__construct($this->data);

    }

    public function formSuccess($filtered_input, $data)
    {
        App::$session->login($filtered_input['email'], $filtered_input['password']);
        header('location:/');
    }

    public function formFail($filtered_input, $data)
    {

        try {
            return $this->render();
        } catch (\Exception $e) {
        }
    }

    public function render($templatePath = '')
    {
        return parent::render('../core/templates/form/form.tpl.php'); // TODO: Change the autogenerated stub
    }
}
